# Homebrew
export HOMEBREW_NO_AUTO_UPDATE=1

# Ruby
export BUNDLE_JOBS=4

# Telemetry
export GATSBY_TELEMETRY_DISABLED=1
export HOMEBREW_NO_ANALYTICS=1
export STNOUPGRADE=1
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export SAM_CLI_TELEMETRY=1
export AZURE_CORE_COLLECT_TELEMETRY=1
export DO_NOT_TRACK=1

# JobScore
export IGNORE_COV='true'
export HUSKY_SKIP_INSTALL=1
export THOR_SILENCE_DEPRECATION=1

alias t='task'
